export const jobCategories = {
  Frontend: [
    "react developer",
    "react engineer",
    "vue.js developer",
    "vue developer",
    "angular developer",
    "angularjs developer",
    "wordpress developer",
    "shopify developer",
    "frontend developer",
    "frontend engineer",
    "front-end developer",
    "front-end engineer",
    "front end developer",
    "front end engineer",
    "react native developer",
    "vue.js frontend developer",
    "wordpress theme developer",
    "wordpress plugin developer",
    "ui/ux engineer",
    "web designer",
    "javascript developer",
    "typescript developer",
    "ui developer",
    "frontend architect",
    "mobile ui designer",
    "mobile ux designer",
  ],
  Backend: [
    "backend developer",
    "backend engineer",
    "back-end developer",
    "back-end engineer",
    "back end developer",
    "back end engineer",
    "node.js developer",
    "node.js engineer",
    "python developer",
    "java developer",
    "ruby on rails developer",
    "php developer",
    "c# developer",
    "asp.net developer",
    ".net developer",
    "sql developer",
    "database administrator",
    "database engineer",
    "backend architect",
    "api developer",
    "middleware developer",
    "microservices developer",
    "crm developer",
  ],
  Fullstack: [
    "fullstack developer",
    "full-stack developer",
    "full stack developer",
    "fullstack engineer",
    "full-stack engineer",
    "full stack engineer",
    "full-stack engineer",
    "fullstack javascript developer",
    "software engineer" 
  ],
  ProductManager: [
    "product manager",
    "product owner",
    "technical project manager",
    "scrum master",
    "agile coach",
    "innovation manager",
  ],
  UXUI: [
    "ux/ui designer",
    "ux designer",
    "ui designer",
    "product designer",
    "user researcher",
    "ui/ux engineer",
    "ux researcher",
    "interaction designer",
    "visual designer",
    "motion designer",
    "graphic designer",
    "mobile ui designer",
    "mobile ux designer",
    "accessibility specialist",
  ],
  QA: [
    "quality assurance (qa) engineer",
    "software tester",
    "test automation engineer",
    "manual qa engineer",
    "game tester",
    "qa analyst",
    "qa specialist",
  ],
  Marketing: [
    "digital marketing specialist",
    "seo specialist",
    "social media manager",
    "marketing automation specialist",
    "email marketing specialist",
    "content manager",
    "content strategist",
    "marketing designer",
    "marketing manager",
    "director of marketing",
    "community manager",
    "community advocate",
    "community facilitator",
    "copywriter",
    "content writer",
    "content marketer",
  ],
  Sales: [
    "pre-sales engineer",
    "post-sales engineer",
    "salesforce administrator",
    "salesforce developer",
    "business development representative",
    "business development manager",
    "enterprise account executive",
    "sales development representative",
    "account manager",
    "account executive",
  ],
  DevOps: [
    "devops engineer",
    "devops specialist",
    "cloud devops engineer",
    "site reliability engineer",
    "software reliability engineer",
    "continuous integration engineer",
    "continuous deployment engineer",
    "infrastructure engineer",
    "platform engineer",
  ],
  DataAnalyst: [
    "data analyst",
    "data scientist",
    "machine learning engineer",
    "artificial intelligence specialist",
    "ai developer",
    "ai engineer",
    "data engineer",
    "big data engineer",
    "bi analyst",
    "bi developer",
    "etl developer",
    "data warehouse specialist",
    "data governance specialist",
    "data privacy officer",
  ],
  CustomerSupport: [
    "customer support specialist",
    "it support specialist",
    "help desk technician",
    "technical support engineer",
    "technical support specialist",
    "customer success manager",
    "customer success specialist",
    "customer solutions engineer",
    "technical account manager",
    "account manager",
    "account executive",
  ],
  VirtualAssistant: [
    "virtual assistant",
    "remote assistant",
    "administrative assistant",
    "executive assistant",
    "personal assistant",
  ],
  Cloud: [
    "cloud engineer",
    "aws developer",
    "azure developer",
    "google cloud platform engineer",
    "cloud solutions architect",
    "solutions architect",
    "technical architect",
  ],
  Security: [
    "cybersecurity analyst",
    "information security analyst",
    "penetration tester",
    "ethical hacker",
    "security engineer",
    "security architect",
    "security analyst",
    "information assurance specialist",
    "compliance officer",
    "risk management specialist",
    "data protection officer",
    "identity and access management specialist",
    "it auditor",
  ],
  MobileDevelopment: [
    "mobile app developer",
    "android developer",
    "android engineer",
    "ios developer",
    "flutter developer",
    "kotlin developer",
    "swift developer",
    "mobile developer",
  ],
  Blockchain: [
    "blockchain developer",
    "smart contract developer",
    "web3 developer",
    "nft developer",
    "blockchain infrastructure engineer",
  ],
  SupportIT: [
    "it support specialist",
    "help desk technician",
    "system administrator",
    "network administrator",
    "it consultant",
    "process engineer",
    "change manager",
    "release manager",
    "service delivery manager",
    "service desk analyst",
    "itil specialist",
    "enterprise architect",
    "engineering manager",
    "chief information officer (cio)",
    "chief technology officer (cto)",
    "it director",
    "it manager",
    "technical lead",
    "content team lead",
    "technical program manager",
  ],
  GameDevelopment: [
    "game developer",
    "game designer",
    "game artist",
    "game producer",
    "level designer",
    "unity developer",
    "unreal engine developer",
  ],
  Robotics: [
    "robotics engineer",
    "automation engineer",
    "firmware developer",
    "embedded systems developer",
    "iot developer",
  ],
  Compliance: [
    "compliance officer",
    "risk management specialist",
    "data protection officer",
    "identity and access management specialist",
    "it auditor",
  ],
  Finance: [
    "finance associate",
    "finance manager",
    "senior accountant",
    "financial analyst",
    "finance director",
  ],
  AI: [
    "ai developer",
    "machine learning engineer",
    "machine learning researcher",
    "ai specialist",
    "data ops engineer",
  ],
  Miscellaneous: [
    "safety specialist",
    "localization expert",
    "translator",
    "developer advocate",
    "success engineer",
    "business analyst",
    "technical writer",
  ],
};
