// Keywords for matching job titles
export const jobKeywords = [
  "React Developer",
  "Vue.js Developer",
  "Angular Developer",
  "WordPress Developer",
  "Shopify Developer",
  "Graphic Designer",
  "Quality Assurance (QA) Engineer",
  "UX/UI Designer",
  "Frontend Developer",
  "Backend Developer",
  "Fullstack Developer",
  "DevOps Engineer",
  "Customer Support Specialist",
  "Product Manager",
  "Product Designer",
  "Technical Support Engineer",
  "Technical Support Specialist",
  "User Researcher",
  "Data Entry Specialist",
  "Account Manager",
  "Account Executive",
  "Finance Associate",
  "Safety Specialist",
  "Uniti Engineer",
  "Subtitler",
  "Localization Expert",
  "Translator",
  "Virtual Assistant",
  "Frontend Engineer",
  "Backend Engineer",
  "Full-stack Engineer",
  "AngularJS Developer",
  "React Native Developer",
  "Vue.js Frontend Developer",
  "WordPress Theme Developer",
  "WordPress Plugin Developer",
  "Shopify App Developer",
  "UI/UX Engineer",
  "Web Designer",
  "Mobile App Developer",
  "JavaScript Developer",
  "TypeScript Developer",
  "Node.js Developer",
  "Node.JS Engineer",
  "Python Developer",
  "Java Developer",
  "Ruby on Rails Developer",
  "PHP Developer",
  "C# Developer",
  "ASP.NET Developer",
  ".NET Developer",
  "Android Developer",
  "Android Engineer",
  "iOS Developer",
  "Flutter Developer",
  "Kotlin Developer",
  "Swift Developer",
  "SQL Developer",
  "Database Administrator",
  "Database Engineer",
  "Data Analyst",
  "Data Scientist",
  "Machine Learning Engineer",
  "Artificial Intelligence Specialist",
  "Cloud Engineer",
  "AWS Developer",
  "Azure Developer",
  "Google Cloud Platform Engineer",
  "Cybersecurity Analyst",
  "Information Security Analyst",
  "Penetration Tester",
  "Ethical Hacker",
  "Network Administrator",
  "System Administrator",
  "IT Support Specialist",
  "Help Desk Technician",
  "Software Engineer",
  "Software Architect",
  "Software Tester",
  "Test Automation Engineer",
  "Continuous Integration Engineer",
  "Continuous Deployment Engineer",
  "DevOps Specialist",
  "Site Reliability Engineer",
  "Software Reliability Engineer",
  "Platform Engineer",
  "Infrastructure Engineer",
  "Cloud Solutions Architect",
  "Solutions Architect",
  "Technical Architect",
  "Business Analyst",
  "Technical Writer",
  "Content Manager",
  "Content Strategist",
  "SEO Specialist",
  "Digital Marketing Specialist",
  "Marketing Automation Specialist",
  "Email Marketing Specialist",
  "Social Media Manager",
  "Community Manager",
  "Customer Success Manager",
  "Customer Success Specialist",
  "Customer Solutions Engineer",
  "Pre-Sales Engineer",
  "Post-Sales Engineer",
  "Salesforce Administrator",
  "Salesforce Developer",
  "CRM Developer",
  "CRM Consultant",
  "ERP Consultant",
  "SAP Consultant",
  "Oracle Developer",
  "SAP ABAP Developer",
  "Microsoft Dynamics Developer",
  "BI (Business Intelligence) Analyst",
  "BI Developer",
  "ETL Developer",
  "Data Warehouse Specialist",
  "Data Governance Specialist",
  "Data Privacy Officer",
  "Information Governance Specialist",
  "Chief Information Officer (CIO)",
  "Chief Technology Officer (CTO)",
  "IT Director",
  "IT Manager",
  "Technical Project Manager",
  "Scrum Master",
  "Agile Coach",
  "Product Owner",
  "UX Researcher",
  "UI Developer",
  "Interaction Designer",
  "Accessibility Specialist",
  "Visual Designer",
  "Motion Designer",
  "3D Animator",
  "Game Developer",
  "Game Designer",
  "Game Tester",
  "Game Artist",
  "Game Producer",
  "Level Designer",
  "Unity Developer",
  "Unreal Engine Developer",
  "Blockchain Developer",
  "Smart Contract Developer",
  "Cryptocurrency Specialist",
  "NFT Developer",
  "Web3 Developer",
  "DevOps Engineer",
  "Cloud DevOps Engineer",
  "Security Engineer",
  "Security Architect",
  "Security Analyst",
  "Information Assurance Specialist",
  "Compliance Officer",
  "Risk Management Specialist",
  "Data Protection Officer",
  "Identity and Access Management Specialist",
  "IT Auditor",
  "IT Consultant",
  "Technical Consultant",
  "Solution Consultant",
  "Process Engineer",
  "Change Manager",
  "Release Manager",
  "Service Delivery Manager",
  "Service Desk Analyst",
  "ITIL Specialist",
  "Enterprise Architect",
  "Enterprise Account Executive",
  "Sales Development Representative",
  "Technical Lead",
  "Content Team Lead",
  "Engineering Manager",
  "Technical Account Manager",
  "Technical Program Manager",
  "Digital Transformation Specialist",
  "Innovation Manager",
  "Mobile Developer",
  "Frontend Architect",
  "Backend Architect",
  "Microservices Developer",
  "API Developer",
  "Integration Specialist",
  "Middleware Developer",
  "Embedded Systems Developer",
  "Firmware Developer",
  "IoT Developer",
  "Robotics Engineer",
  "Automation Engineer",
  "AI Developer",
  "Machine Learning Researcher",
  "Data Engineer",
  "Data Ops Engineer",
  "Big Data Engineer",
  "Hadoop Developer",
  "Spark Developer",
  "Kafka Developer",
  "ElasticSearch Developer",
  "Fullstack JavaScript Developer",
  "Front-end Engineer",
  "Back-end Engineer",
  "Mobile UI Designer",
  "Mobile UX Designer",
  "Front-end Web Developer",
  "Back-end Web Developer",
  "Developer Advocate",
  "Success Engineer",
  "Full Stack Developer",
  "Marketing Designer",
  "Community Advocate",
  "Copywriter",
  "Content Writer",
  "Web Engineer",
  "Marketing Manager",
  "Finance Manager",
  "Director of Marketing",
  "Business Development Representative",
  "Business Development Manager",
  "Blockchain Infrastructure Engineer",
  "Senior Accountant",
  "React Engineer",
  "MQA Engineer",
  "GO Developer",
  "Community Facilitator",
  "English Teacher",
  "French Teacher",
  "German Teacher",
  "Spanish Teacher",
];
